### ISSUE TITLE
gallery: tekst

### ISSUE THREAD

**Issue by janlipinski** [kemblan/sweetunique#24]
tekst nie ma przypisanych cssów

**Comment by marcinNS** [comment]
?

**Comment by janlipinski** [comment]
new gallery i desc mimo, że są jakąś formą nagłówka i tekstu, to wyświetla mi się times new roman
http://www.groktheme.com/sweetunique/gallery/

**Comment by marcinNS** [comment]
dałem czcionkę 'Gorditas' tylko dla tytułu.
dla opisu 'Open Sans'
