### ISSUE TITLE
gallery: border

### ISSUE THREAD

**Issue by janlipinski** [kemblan/sweetunique#25]
na hoverze zdjęcia zmieniają pozycję

**Comment by marcinNS** [comment]
to było zmieniane, czy teraz też jest źle?

**Comment by janlipinski** [comment]
kiedy najeżdżam kursorem, border widać tylko na górze i z lewej strony:
http://www.groktheme.com/sweetunique/gallery/
![zrzut ekranu 2015-04-15 o 11 10 26](https://cloud.githubusercontent.com/assets/10222501/7155569/0abd39e8-e360-11e4-95ad-015a9fac23af.png)

**Comment by marcinNS** [comment]
zriobione
