### ISSUE TITLE
contact: formularz

### ISSUE THREAD

**Issue by janlipinski** [kemblan/sweetunique#26]
do zmiany jest przycisk (style i wyrównanie do prawej krawędzi)

nie ma jakiejś ładniejszej formy sprawdzenia użytkownika? widziałem czasem proste działanie matematyczne, wyglądałoby ładniej...

name, email, message w środku boxów

wyrównanie szerokości pól (obecnie text-area jest wyrównana do prawej krawędzi, ale pozostałe nie)

**Comment by marcinNS** [comment]
proszę zaproponować jakiś inny captcha,
reszta jest zrobiona

**Comment by janlipinski** [comment]
u mnie ten formularz do końca się trzyma:
jest za wysoko, captcha za szeroka
![zrzut ekranu 2015-04-15 o 11 17 15](https://cloud.githubusercontent.com/assets/10222501/7155706/0aa0ebfc-e361-11e4-9b88-b2ad7d7bdc25.png)

**Comment by marcinNS** [comment]
poprawiono, dałem górny margines 
wygląd captcha https://developers.google.com/recaptcha/old/docs/customization
