### ISSUE TITLE
Twiitter, Facebook 

### ISSUE THREAD

**Issue by kemblan** [kemblan/sweetunique#28]
Prosba o przenuniecie do gory - Janku zaproponuje miejsce

**Comment by marcinNS** [comment]
ok, czekam na propozycje

**Comment by janlipinski** [comment]
http://cl.ly/1I0j1o1o3Y3j
a niech wygląda tak:
![zrzut ekranu 2015-04-15 o 11 35 17](https://cloud.githubusercontent.com/assets/10222501/7156009/8b21ec98-e363-11e4-857d-f6e9c48ba6a9.png)

**Comment by marcinNS** [comment]
zmieniłem
