### ISSUE TITLE
Zmiana noc/dzien

### ISSUE THREAD

**Issue by kemblan** [kemblan/sweetunique#3]
Zmiana noc dzien powoduje przejcie z homepage na kontakt

**Comment by marcinNS** [comment]
Jest problem z ustawieniem tego na stronie głównej. Źle przekierowuje ruch tzn. nie kieruje na stronę główną tylko na strone z wpisami.

Jednak nie ma problemu na wszystkich innych podstronach np. http://www.groktheme.com/sweetunique/presets/
