### ISSUE TITLE
Nowe zdjecie na strone glowna

### ISSUE THREAD

**Issue by kemblan** [kemblan/sweetunique#5]
Janku, prosze o zlozenie z istniejacych zdjec kolazu ktory bylby podobnej wielkosci co to zdjecie ktore jest teraz

**Comment by kemblan** [comment]
Janku?

**Comment by janlipinski** [comment]
![childrens02](https://cloud.githubusercontent.com/assets/10222501/7107828/5d7d0b94-e172-11e4-86d9-f813ae7c5862.jpg)

**Comment by janlipinski** [comment]
![childrens-02](https://cloud.githubusercontent.com/assets/10222501/7107833/755ebe2e-e172-11e4-9b6b-9767bfb5b9fc.jpg)

**Comment by marcinNS** [comment]
zmieniłem
