### ISSUE TITLE
slider: strzałki

### ISSUE THREAD

**Issue by janlipinski** [kemblan/sweetunique#9]
strzałki nie są wyrównane (potrzeba obniżyć o 5px)

**Comment by marcinNS** [comment]
zmieniłem zadanie na "dodać strzałki"
proszę o sprawdzenie czy taki mogą być.
są to zdjęcia, więc ewentualnie proszę przesłać png z strzałkami jak to ma wyglądać

**Comment by janlipinski** [comment]
![bt-next](https://cloud.githubusercontent.com/assets/10222501/7155181/e2fe355e-e35c-11e4-9119-ebb1e3f00953.png)
![bt-prev](https://cloud.githubusercontent.com/assets/10222501/7155180/e2edd434-e35c-11e4-9fe1-7ff2659ccc4b.png)

poproszę takie, są subtelniejsze.

**Comment by janlipinski** [comment]
gdyby był problem z wzięciem obrazków na górze:
http://cl.ly/022g0T0k0N3T

**Comment by marcinNS** [comment]
zrobione

**Comment by janlipinski** [comment]
strzałki są za duże/niezmienione
